version: '3.5'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test

  bot:
    image: somnium11/bot2_wkpd
    environment:
      CREATE_TABLE: "yes"
      DB_SWITCH: "on"
      TOKEN: 7316017247:AAGVDTlqNL49yJtx2fv4oa_U8qQdw3Jr7l0
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD: test
      DBNAME: postgres
      SSLMODE: disable

      