version: '3.5'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test

  bot:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      CREATE_TABLE: "yes"
      DB_SWITCH: "on"
      TOKEN: 7360626109:AAGuxcqygabwNPC68jtAtu3k0TP_lDaJroU
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD: test
      DBNAME: postgres
      SSLMODE: disable
      